// Dummy data for financial transactions
export const dummyTransactions = [
  {
    id: 1,
    date: '2023-06-15',
    description: 'Gaji Bulanan',
    amount: 15000000,
    type: 'income',
    account: 'BCA Tabungan',
    category: 'Gaji',
    group: 'Keluarga',
  },
  {
    id: 2,
    date: '2023-06-10',
    description: 'Belanja Bulanan',
    amount: -2500000,
    type: 'expense',
    account: 'OVO',
    category: 'Makanan & Minuman',
    group: 'Keluarga',
  },
  {
    id: 3,
    date: '2023-06-05',
    description: 'Transport ke Kantor',
    amount: -50000,
    type: 'expense',
    account: 'Cash Wallet',
    category: 'Transportasi',
    group: 'Keluarga',
  },
  {
    id: 4,
    date: '2023-06-01',
    description: 'Investasi Reksa Dana',
    amount: -1000000,
    type: 'expense',
    account: 'Mandiri Tabungan',
    category: 'Investasi',
    group: 'Investasi Bareng',
  },
  {
    id: 5,
    date: '2023-05-28',
    description: 'Bonus Proyek',
    amount: 5000000,
    type: 'income',
    account: 'BCA Tabungan',
    category: 'Bonus',
    group: 'Keluarga',
  },
  {
    id: 6,
    date: '2023-05-20',
    description: 'Makan Malam',
    amount: -150000,
    type: 'expense',
    account: 'OVO',
    category: 'Makanan & Minuman',
    group: 'Keluarga',
  },
  {
    id: 7,
    date: '2023-05-15',
    description: 'Dividen Saham',
    amount: 750000,
    type: 'income',
    account: 'BCA Tabungan',
    category: 'Investasi',
    group: 'Investasi Bareng',
  },
  {
    id: 8,
    date: '2023-05-10',
    description: 'Bayar Listrik',
    amount: -300000,
    type: 'expense',
    account: 'BCA Tabungan',
    category: 'Utilitas',
    group: 'Keluarga',
  },
  {
    id: 9,
    date: '2023-05-05',
    description: 'Beli Bahan Makanan',
    amount: -450000,
    type: 'expense',
    account: 'OVO',
    category: 'Makanan & Minuman',
    group: 'Keluarga',
  },
  {
    id: 10,
    date: '2023-04-30',
    description: 'Gaji Bulanan',
    amount: 15000000,
    type: 'income',
    account: 'BCA Tabungan',
    category: 'Gaji',
    group: 'Keluarga',
  },
  {
    id: 11,
    date: '2023-04-25',
    description: 'Bayar Cicilan Motor',
    amount: -1200000,
    type: 'expense',
    account: 'BCA Tabungan',
    category: 'Transportasi',
    group: 'Keluarga',
  },
  {
    id: 12,
    date: '2023-04-20',
    description: 'Makan Siang Meeting',
    amount: -85000,
    type: 'expense',
    account: 'OVO',
    category: 'Makanan & Minuman',
    group: 'Keluarga',
  },
  {
    id: 13,
    date: '2023-04-15',
    description: 'Investasi Emas',
    amount: -2000000,
    type: 'expense',
    account: 'Mandiri Tabungan',
    category: 'Investasi',
    group: 'Investasi Bareng',
  },
  {
    id: 14,
    date: '2023-04-10',
    description: 'Freelance Project',
    amount: 3500000,
    type: 'income',
    account: 'OVO',
    category: 'Pendapatan Tambahan',
    group: 'Keluarga',
  },
  {
    id: 15,
    date: '2023-04-05',
    description: 'Bayar Internet',
    amount: -250000,
    type: 'expense',
    account: 'BCA Tabungan',
    category: 'Utilitas',
    group: 'Keluarga',
  },
];
